ALTER TABLE contacts ADD COLUMN youtube TEXT NOT NULL DEFAULT '';
ALTER TABLE contacts ADD COLUMN facebook TEXT NOT NULL DEFAULT '';
ALTER TABLE contacts ADD COLUMN instagram TEXT NOT NULL DEFAULT '';
ALTER TABLE organisations ADD COLUMN youtube TEXT NOT NULL DEFAULT '';
ALTER TABLE organisations ADD COLUMN facebook TEXT NOT NULL DEFAULT '';
ALTER TABLE organisations ADD COLUMN instagram TEXT NOT NULL DEFAULT '';